name: Send Email

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email using Resend API
        run: |
          curl -X POST https://api.resend.com/emails \
            -H "Authorization: Bearer ${{ secrets.RESEND_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "from": "Credition Finance <creditionusa@gmail.com>",
              "to": ["recipient@example.com"],
              "subject": "Request for free consultation",
              "html": "<strong>Hello from GitHub + Resend!</strong>"
            }'
